
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 1212
 */
public class Menu extends javax.swing.JFrame {
    String host,userName,password;
    Connection con;
    Statement stmt;
    String sqlStatement;
    ResultSet rs;
    String a,b;
        int c,d,e;

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        try{
             host="jdbc:mysql://localhost:3306/freshqo";
             userName="root";
             password="carbon12";
            con=DriverManager.getConnection(host,userName,password);
            stmt=con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_UPDATABLE);
            sqlStatement="Select * from ORDERS";
            rs=stmt.executeQuery(sqlStatement);
            rs.last();
        }
          catch(SQLException e){
            System.out.println(e.getMessage());
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jCheckBox31 = new javax.swing.JCheckBox();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jCheckBox9 = new javax.swing.JCheckBox();
        jCheckBox10 = new javax.swing.JCheckBox();
        jCheckBox11 = new javax.swing.JCheckBox();
        jCheckBox12 = new javax.swing.JCheckBox();
        jCheckBox13 = new javax.swing.JCheckBox();
        jCheckBox14 = new javax.swing.JCheckBox();
        jCheckBox15 = new javax.swing.JCheckBox();
        jCheckBox16 = new javax.swing.JCheckBox();
        jCheckBox17 = new javax.swing.JCheckBox();
        jCheckBox18 = new javax.swing.JCheckBox();
        jCheckBox19 = new javax.swing.JCheckBox();
        jCheckBox20 = new javax.swing.JCheckBox();
        jCheckBox21 = new javax.swing.JCheckBox();
        jCheckBox22 = new javax.swing.JCheckBox();
        jCheckBox24 = new javax.swing.JCheckBox();
        jCheckBox23 = new javax.swing.JCheckBox();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();

        jCheckBox31.setText("jCheckBox31");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 255, 204));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel1.setText("MENU");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jCheckBox1.setText("CHICKEN MANCHURIAN");

        jCheckBox2.setText("CHICKEN LOLLIPOP");

        jCheckBox3.setText("FISH CURRY");

        jCheckBox4.setText("BASIL CHICKEN");

        jCheckBox5.setText("BAKED PRAWNS");

        jCheckBox6.setText("SALAMI SANDWICH");

        jCheckBox7.setText("STEAMED RICE");

        jCheckBox8.setText("HAKKA NOODLES");
        jCheckBox8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox8ActionPerformed(evt);
            }
        });

        jCheckBox9.setText("THAI CURRY");

        jCheckBox10.setText("ARRIABATA PASTA");

        jCheckBox11.setText("VEG DIMSUMS");

        jCheckBox12.setText("VEG MANCHURIAN");

        jCheckBox13.setText("JAIN MIXED VEG");

        jCheckBox14.setText("DHOKLA");

        jCheckBox15.setText("DAL MAKHNI");

        jCheckBox16.setText("BANANA CHIPS");

        jCheckBox17.setText("VEG PULAO");

        jCheckBox18.setText("SALAD");

        jCheckBox19.setText("VEG ROLL");

        jCheckBox20.setText("CHICKEN ROLL");

        jCheckBox21.setText("MALAI CHAP");

        jCheckBox22.setText("CHICKEN BIRYANI");

        jCheckBox24.setText("RAITA");

        jCheckBox23.setText("BUTTER CHICKEN");
        jCheckBox23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox23ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox1)
                            .addComponent(jCheckBox2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox7)
                            .addComponent(jCheckBox8)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox3)
                            .addComponent(jCheckBox4)
                            .addComponent(jCheckBox5)
                            .addComponent(jCheckBox6))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox12)
                            .addComponent(jCheckBox10)
                            .addComponent(jCheckBox9)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jCheckBox11)
                                .addGap(99, 99, 99)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jCheckBox13)
                                            .addComponent(jCheckBox15)
                                            .addComponent(jCheckBox16))
                                        .addGap(36, 36, 36)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jCheckBox22)
                                            .addComponent(jCheckBox21)
                                            .addComponent(jCheckBox20)
                                            .addComponent(jCheckBox19)))
                                    .addComponent(jCheckBox14)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jCheckBox18)
                                            .addComponent(jCheckBox17))
                                        .addGap(60, 60, 60)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jCheckBox23)
                                            .addComponent(jCheckBox24))))))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox1)
                    .addComponent(jCheckBox7)
                    .addComponent(jCheckBox13)
                    .addComponent(jCheckBox19))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox2)
                    .addComponent(jCheckBox8)
                    .addComponent(jCheckBox14)
                    .addComponent(jCheckBox20))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox3)
                    .addComponent(jCheckBox9)
                    .addComponent(jCheckBox15)
                    .addComponent(jCheckBox21))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox4)
                    .addComponent(jCheckBox10)
                    .addComponent(jCheckBox16)
                    .addComponent(jCheckBox22))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox5)
                    .addComponent(jCheckBox11)
                    .addComponent(jCheckBox17)
                    .addComponent(jCheckBox23))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox6)
                    .addComponent(jCheckBox12)
                    .addComponent(jCheckBox18)
                    .addComponent(jCheckBox24))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("VEGETARIAN");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("JAIN");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        jButton1.setText("SELECT QUANTITY");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("NON-VEG");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(224, 224, 224)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jRadioButton3)
                                        .addGap(63, 63, 63)
                                        .addComponent(jRadioButton1)
                                        .addGap(45, 45, 45)
                                        .addComponent(jRadioButton2)
                                        .addGap(141, 141, 141))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(254, 254, 254)))))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton2)
                            .addComponent(jRadioButton3)
                            .addComponent(jRadioButton1))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(jButton1)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox8ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jCheckBox8ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
        jCheckBox1.setEnabled(true);
        jCheckBox2.setEnabled(true);
        jCheckBox3.setEnabled(true);
        jCheckBox4.setEnabled(true);
        jCheckBox5.setEnabled(true);
        jCheckBox6.setEnabled(true);
        jCheckBox7.setEnabled(true);
        jCheckBox8.setEnabled(true);
        jCheckBox9.setEnabled(true);
        jCheckBox10.setEnabled(true);
        jCheckBox11.setEnabled(true);
        jCheckBox12.setEnabled(true);
        jCheckBox13.setEnabled(true);
        jCheckBox14.setEnabled(true);
        jCheckBox15.setEnabled(true);
        jCheckBox16.setEnabled(true);
        jCheckBox17.setEnabled(true);
        jCheckBox18.setEnabled(true);
        jCheckBox19.setEnabled(true);
        jCheckBox20.setEnabled(true);
        jCheckBox21.setEnabled(true);
        jCheckBox22.setEnabled(true);
        jCheckBox23.setEnabled(true);
        jCheckBox24.setEnabled(true);
        jCheckBox1.setEnabled(false);
        jCheckBox2.setEnabled(false);
        jCheckBox3.setEnabled(false);
        jCheckBox4.setEnabled(false);
        jCheckBox5.setEnabled(false);
        jCheckBox6.setEnabled(false);
        jCheckBox8.setEnabled(false);
        jCheckBox9.setEnabled(false);
        jCheckBox10.setEnabled(false);
        jCheckBox11.setEnabled(false);
        jCheckBox12.setEnabled(false);
        jCheckBox23.setEnabled(false);
        jCheckBox19.setEnabled(false);
        jCheckBox20.setEnabled(false);
        jCheckBox21.setEnabled(false);
        jCheckBox22.setEnabled(false);
        
        
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
           jCheckBox1.setEnabled(true);
        jCheckBox2.setEnabled(true);
        jCheckBox3.setEnabled(true);
        jCheckBox4.setEnabled(true);
        jCheckBox5.setEnabled(true);
        jCheckBox6.setEnabled(true);
        jCheckBox7.setEnabled(true);
        jCheckBox8.setEnabled(true);
        jCheckBox9.setEnabled(true);
        jCheckBox10.setEnabled(true);
        jCheckBox11.setEnabled(true);
        jCheckBox12.setEnabled(true);
        jCheckBox13.setEnabled(true);
        jCheckBox14.setEnabled(true);
        jCheckBox15.setEnabled(true);
        jCheckBox16.setEnabled(true);
        jCheckBox17.setEnabled(true);
        jCheckBox18.setEnabled(true);
        jCheckBox19.setEnabled(true);
        jCheckBox20.setEnabled(true);
        jCheckBox21.setEnabled(true);
        jCheckBox22.setEnabled(true);
        jCheckBox23.setEnabled(true);
        jCheckBox24.setEnabled(true);
        jCheckBox7.setEnabled(false);
        jCheckBox8.setEnabled(false);
        jCheckBox9.setEnabled(false);
        jCheckBox10.setEnabled(false);
        jCheckBox11.setEnabled(false);
        jCheckBox12.setEnabled(false);
        jCheckBox13.setEnabled(false);
        jCheckBox14.setEnabled(false);
        jCheckBox15.setEnabled(false);
        jCheckBox16.setEnabled(false);
        jCheckBox18.setEnabled(false);
        jCheckBox19.setEnabled(false);
        jCheckBox21.setEnabled(false);
        jCheckBox17.setEnabled(false);
        jCheckBox24.setEnabled(false);
        
        
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
          jCheckBox1.setEnabled(true);
        jCheckBox2.setEnabled(true);
        jCheckBox3.setEnabled(true);
        jCheckBox4.setEnabled(true);
        jCheckBox5.setEnabled(true);
        jCheckBox6.setEnabled(true);
        jCheckBox7.setEnabled(true);
        jCheckBox8.setEnabled(true);
        jCheckBox9.setEnabled(true);
        jCheckBox10.setEnabled(true);
        jCheckBox11.setEnabled(true);
        jCheckBox12.setEnabled(true);
        jCheckBox13.setEnabled(true);
        jCheckBox14.setEnabled(true);
        jCheckBox15.setEnabled(true);
        jCheckBox16.setEnabled(true);
        jCheckBox17.setEnabled(true);
        jCheckBox18.setEnabled(true);
        jCheckBox19.setEnabled(true);
        jCheckBox20.setEnabled(true);
        jCheckBox21.setEnabled(true);
        jCheckBox22.setEnabled(true);
        jCheckBox23.setEnabled(true);
        jCheckBox24.setEnabled(true);
        jCheckBox1.setEnabled(false);
        jCheckBox2.setEnabled(false);
        jCheckBox3.setEnabled(false);
        jCheckBox4.setEnabled(false);
        jCheckBox5.setEnabled(false);
        jCheckBox6.setEnabled(false);
        jCheckBox20.setEnabled(false);
        jCheckBox22.setEnabled(false);
        jCheckBox23.setEnabled(false);
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jCheckBox23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox23ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        d=0;
        b="";
        a="";
        if(jCheckBox1.isSelected()==true)
        {
            a=JOptionPane.showInputDialog("SELECT SIZE CHICKEN MANCHURIAN");
            if(a.equals("s")==true||a.equals("m")==true||a.equals("l")==true)
            {
            }
            else
            {
                a=JOptionPane.showInputDialog("PLEASE ENTER FROM THE FOLLOWING OPTION (s,m,l)");
            }
            b=b+"CHICKEN MANCHURIAN"+"("+a+")"+"\n";
            if(a.equals("s")==true)
            {
                c=200;
            }
            else if(a.equals("m"))
            {
                c=300;
            }
            else
            {
                c=400;
            }
            d=d+c;
        }
        if(jCheckBox2.isSelected()==true)
        {
            a=JOptionPane.showInputDialog("SELECT SIZE CHICKEN LOLLIPOP");
            if(a.equals("s")==true||a.equals("m")==true||a.equals("l")==true)
            {
            }
            else
            {
                a=JOptionPane.showInputDialog("PLEASE ENTER FROM THE FOLLOWING OPTION (s,m,l)");
            }
            b=b+"CHICKEN LOLLIPOP"+"("+a+")"+"\n";
            if(a.equals("s")==true)
            {
                c=200;
            }
            else if(a.equals("m"))
            {
                c=300;
            }
            else
            {
                c=400;
            }
            d=d+c;
        }
        if(jCheckBox3.isSelected()==true)
        {
            a=JOptionPane.showInputDialog("SELECT SIZE FISH CURRY");
            if(a.equals("s")==true||a.equals("m")==true||a.equals("l")==true)
            {
            }
            else
            {
                a=JOptionPane.showInputDialog("PLEASE ENTER FROM THE FOLLOWING OPTION (s,m,l)");
            }
            b=b+"FISH CURRY"+"("+a+")"+"\n";
            if(a.equals("s")==true)
            {
                c=200;
            }
            else if(a.equals("m"))
            {
                c=300;
            }
            else
            {
                c=400;
            }
            d=d+c;
        }
        if(jCheckBox4.isSelected()==true)
        {
            a=JOptionPane.showInputDialog("SELECT SIZE BASIL CHICKEN");
            if(a.equals("s")==true||a.equals("m")==true||a.equals("l")==true)
            {
            }
            else
            {
                a=JOptionPane.showInputDialog("PLEASE ENTER FROM THE FOLLOWING OPTION (s,m,l)");
            }
            b=b+"BASIL CHICKEN"+"("+a+")"+"\n";
            if(a.equals("s")==true)
            {
                c=200;
            }
            else if(a.equals("m"))
            {
                c=300;
            }
            else
            {
                c=400;
            }
            d=d+c;
        }
        if(jCheckBox5.isSelected()==true)
        {
            a=JOptionPane.showInputDialog("SELECT SIZE BAKED PRAWNS");
            if(a.equals("s")==true||a.equals("m")==true||a.equals("l")==true)
            {
            }
            else
            {
                a=JOptionPane.showInputDialog("PLEASE ENTER FROM THE FOLLOWING OPTION (s,m,l)");
            }
            b=b+"BAKED PRAWNS"+"("+a+")"+"\n";
            if(a.equals("s")==true)
            {
                c=200;
            }
            else if(a.equals("m"))
            {
                c=300;
            }
            else
            {
                c=400;
            }
            d=d+c;
        }
        if(jCheckBox6.isSelected()==true)
        {
            a=JOptionPane.showInputDialog("SELECT SIZE SALAMI SANDWICH");
            if(a.equals("s")==true||a.equals("m")==true||a.equals("l")==true)
            {
            }
            else
            {
                a=JOptionPane.showInputDialog("PLEASE ENTER FROM THE FOLLOWING OPTION (s,m,l)");
            }
            b=b+"SALAMI SANDWICH"+"("+a+")"+"\n";
            if(a.equals("s")==true)
            {
                c=200;
            }
            else if(a.equals("m"))
            {
                c=300;
            }
            else
            {
                c=400;
            }
            d=d+c;
        }
        if(jCheckBox7.isSelected()==true)
        {
            a=JOptionPane.showInputDialog("SELECT SIZE STEAMED RICE");
            if(a.equals("s")==true||a.equals("m")==true||a.equals("l")==true)
            {
            }
            else
            {
                a=JOptionPane.showInputDialog("PLEASE ENTER FROM THE FOLLOWING OPTION (s,m,l)");
            }
            b=b+"STEAMED RICE"+"("+a+")"+"\n";
            if(a.equals("s")==true)
            {
                c=200;
            }
            else if(a.equals("m"))
            {
                c=300;
            }
            else
            {
                c=400;
            }
            d=d+c;
        }
        if(jCheckBox8.isSelected()==true)
        {
            a=JOptionPane.showInputDialog("SELECT SIZE HAKKA NOODLES");
            if(a.equals("s")==true||a.equals("m")==true||a.equals("l")==true)
            {
            }
            else
            {
                a=JOptionPane.showInputDialog("PLEASE ENTER FROM THE FOLLOWING OPTION (s,m,l)");
            }
            b=b+"HAKKA NOODLES"+"("+a+")"+"\n";
            if(a.equals("s")==true)
            {
                c=200;
            }
            else if(a.equals("m"))
            {
                c=300;
            }
            else
            {
                c=400;
            }
            d=d+c;
        }
        if(jCheckBox9.isSelected()==true)
        {
            a=JOptionPane.showInputDialog("SELECT SIZE THAI CURRY");
            if(a.equals("s")==true||a.equals("m")==true||a.equals("l")==true)
            {
            }
            else
            {
                a=JOptionPane.showInputDialog("PLEASE ENTER FROM THE FOLLOWING OPTION (s,m,l)");
            }
            b=b+"THAI CURRY"+"("+a+")"+"\n";
            if(a.equals("s")==true)
            {
                c=200;
            }
            else if(a.equals("m"))
            {
                c=300;
            }
            else
            {
                c=400;
            }
            d=d+c;
        }
        if(jCheckBox10.isSelected()==true)
        {
            a=JOptionPane.showInputDialog("SELECT SIZE ARIABATTA PASTA");
            if(a.equals("s")==true||a.equals("m")==true||a.equals("l")==true)
            {
            }
            else
            {
                a=JOptionPane.showInputDialog("PLEASE ENTER FROM THE FOLLOWING OPTION (s,m,l)");
            }
            b=b+"ARIABATTA PASTA"+"("+a+")"+"\n";
            if(a.equals("s")==true)
            {
                c=200;
            }
            else if(a.equals("m"))
            {
                c=300;
            }
            else
            {
                c=400;
            }
            d=d+c;
        }
        if(jCheckBox11.isSelected()==true)
        {
            a=JOptionPane.showInputDialog("SELECT SIZE VEG DIMSUMS");
            if(a.equals("s")==true||a.equals("m")==true||a.equals("l")==true)
            {
            }
            else
            {
                a=JOptionPane.showInputDialog("PLEASE ENTER FROM THE FOLLOWING OPTION (s,m,l)");
            }
            b=b+"VEG DIMSUMS"+"("+a+")"+"\n";
            if(a.equals("s")==true)
            {
                c=200;
            }
            else if(a.equals("m"))
            {
                c=300;
            }
            else
            {
                c=400;
            }
            d=d+c;
        }
        if(jCheckBox12.isSelected()==true)
        {
            a=JOptionPane.showInputDialog("SELECT SIZE RAITA");
            if(a.equals("s")==true||a.equals("m")==true||a.equals("l")==true)
            {
            }
            else
            {
                a=JOptionPane.showInputDialog("PLEASE ENTER FROM THE FOLLOWING OPTION (s,m,l)");
            }
            b=b+"VEG MANCHURIAN"+"("+a+")"+"\n";
            if(a.equals("s")==true)
            {
                c=200;
            }
            else if(a.equals("m"))
            {
                c=300;
            }
            else
            {
                c=400;
            }
            d=d+c;
        }
        if(jCheckBox13.isSelected()==true)
        {
            a=JOptionPane.showInputDialog("SELECT SIZE RAITA");
            if(a.equals("s")==true||a.equals("m")==true||a.equals("l")==true)
            {
            }
            else
            {
                a=JOptionPane.showInputDialog("PLEASE ENTER FROM THE FOLLOWING OPTION (s,m,l)");
            }
            b=b+"JAIN MIXED VEG"+"("+a+")"+"\n";
            if(a.equals("s")==true)
            {
                c=200;
            }
            else if(a.equals("m"))
            {
                c=300;
            }
            else
            {
                c=400;
            }
            d=d+c;
        }
        if(jCheckBox14.isSelected()==true)
        {
            a=JOptionPane.showInputDialog("SELECT SIZE RAITA");
            if(a.equals("s")==true||a.equals("m")==true||a.equals("l")==true)
            {
            }
            else
            {
                a=JOptionPane.showInputDialog("PLEASE ENTER FROM THE FOLLOWING OPTION (s,m,l)");
            }
            b=b+"DHOKLA"+"("+a+")"+"\n";
            if(a.equals("s")==true)
            {
                c=200;
            }
            else if(a.equals("m"))
            {
                c=300;
            }
            else
            {
                c=400;
            }
            d=d+c;
        }
        if(jCheckBox15.isSelected()==true)
        {
            a=JOptionPane.showInputDialog("SELECT SIZE RAITA");
            if(a.equals("s")==true||a.equals("m")==true||a.equals("l")==true)
            {
            }
            else
            {
                a=JOptionPane.showInputDialog("PLEASE ENTER FROM THE FOLLOWING OPTION (s,m,l)");
            }
            b=b+"DAL MAKHNI"+"("+a+")"+"\n";
            if(a.equals("s")==true)
            {
                c=200;
            }
            else if(a.equals("m"))
            {
                c=300;
            }
            else
            {
                c=400;
            }
            d=d+c;
        }
        if(jCheckBox16.isSelected()==true)
        {
            a=JOptionPane.showInputDialog("SELECT SIZE RAITA");
            if(a.equals("s")==true||a.equals("m")==true||a.equals("l")==true)
            {
            }
            else
            {
                a=JOptionPane.showInputDialog("PLEASE ENTER FROM THE FOLLOWING OPTION (s,m,l)");
            }
            b=b+"BANANA CHIPS"+"("+a+")"+"\n";
            if(a.equals("s")==true)
            {
                c=200;
            }
            else if(a.equals("m"))
            {
                c=300;
            }
            else
            {
                c=400;
            }
            d=d+c;
        }
        if(jCheckBox17.isSelected()==true)
        {
            a=JOptionPane.showInputDialog("SELECT SIZE RAITA");
            if(a.equals("s")==true||a.equals("m")==true||a.equals("l")==true)
            {
            }
            else
            {
                a=JOptionPane.showInputDialog("PLEASE ENTER FROM THE FOLLOWING OPTION (s,m,l)");
            }
            b=b+"VEG PULAO"+"("+a+")"+"\n";
            if(a.equals("s")==true)
            {
                c=200;
            }
            else if(a.equals("m"))
            {
                c=300;
            }
            else
            {
                c=400;
            }
            d=d+c;
        }
        if(jCheckBox18.isSelected()==true)
        {
            a=JOptionPane.showInputDialog("SELECT SIZE SALAD");
            if(a.equals("s")==true||a.equals("m")==true||a.equals("l")==true)
            {
            }
            else
            {
                a=JOptionPane.showInputDialog("PLEASE ENTER FROM THE FOLLOWING OPTION (s,m,l)");
            }
            b=b+"SALAD"+"("+a+")"+"\n";
            if(a.equals("s")==true)
            {
                c=200;
            }
            else if(a.equals("m"))
            {
                c=300;
            }
            else
            {
                c=400;
            }
            d=d+c;
        }
        if(jCheckBox19.isSelected()==true)
        {
            a=JOptionPane.showInputDialog("SELECT SIZE VEG ROLL");
            if(a.equals("s")==true||a.equals("m")==true||a.equals("l")==true)
            {
            }
            else
            {
                a=JOptionPane.showInputDialog("PLEASE ENTER FROM THE FOLLOWING OPTION (s,m,l)");
            }
            b=b+"VEG ROLL"+"("+a+")"+"\n";
            if(a.equals("s")==true)
            {
                c=200;
            }
            else if(a.equals("m"))
            {
                c=300;
            }
            else
            {
                c=400;
            }
            d=d+c;
        }
        if(jCheckBox20.isSelected()==true)
        {
            a=JOptionPane.showInputDialog("SELECT SIZE CHICKEN ROLL");
            if(a.equals("s")==true||a.equals("m")==true||a.equals("l")==true)
            {
            }
            else
            {
                a=JOptionPane.showInputDialog("PLEASE ENTER FROM THE FOLLOWING OPTION (s,m,l)");
            }
            b=b+"CHICKEN ROLL"+"("+a+")"+"\n";
            if(a.equals("s")==true)
            {
                c=200;
            }
            else if(a.equals("m"))
            {
                c=300;
            }
            else
            {
                c=400;
            }
            d=d+c;
        }
        if(jCheckBox21.isSelected()==true)
        {
            a=JOptionPane.showInputDialog("SELECT SIZE MALAI CHAP");
            if(a.equals("s")==true||a.equals("m")==true||a.equals("l")==true)
            {
            }
            else
            {
                a=JOptionPane.showInputDialog("PLEASE ENTER FROM THE FOLLOWING OPTION (s,m,l)");
            }
            b=b+"MALAI CHAP"+"("+a+")"+"\n";
            if(a.equals("s")==true)
            {
                c=200;
            }
            else if(a.equals("m"))
            {
                c=300;
            }
            else
            {
                c=400;
            }
            d=d+c;
        }
        if(jCheckBox22.isSelected()==true)
        {
            a=JOptionPane.showInputDialog("SELECT SIZE CHICKEN BIRYANI");
            if(a.equals("s")==true||a.equals("m")==true||a.equals("l")==true)
            {
            }
            else
            {
                a=JOptionPane.showInputDialog("PLEASE ENTER FROM THE FOLLOWING OPTION (s,m,l)");
            }
            b=b+"CHICKEN BIRYANI"+"("+a+")"+"\n";
            if(a.equals("s")==true)
            {
                c=200;
            }
            else if(a.equals("m"))
            {
                c=300;
            }
            else
            {
                c=400;
            }
            d=d+c;
        }
        if(jCheckBox23.isSelected()==true)
        {
            a=JOptionPane.showInputDialog("SELECT SIZE BUTTER CHICKEN");
            if(a.equals("s")==true||a.equals("m")==true||a.equals("l")==true)
            {
            }
            else
            {
                a=JOptionPane.showInputDialog("PLEASE ENTER FROM THE FOLLOWING OPTION (s,m,l)");
            }
            b=b+"BUTTER CHCIKEN"+"("+a+")"+"\n";
            if(a.equals("s")==true)
            {
                c=200;
            }
            else if(a.equals("m"))
            {
                c=300;
            }
            else
            {
                c=400;
            }
            d=d+c;
        }
        if(jCheckBox24.isSelected()==true)
        {
            a=JOptionPane.showInputDialog("SELECT SIZE RAITA");
            if(a.equals("s")==true||a.equals("m")==true||a.equals("l")==true)
            {
            }
            else
            {
                a=JOptionPane.showInputDialog("PLEASE ENTER FROM THE FOLLOWING OPTION (s,m,l)");
            }
            b=b+"RAITA"+"("+a+")"+"\n";
            if(a.equals("s")==true)
            {
                c=200;
            }
            else if(a.equals("m"))
            {
                c=300;
            }
            else
            {
                c=400;
            }
            d=d+c;

        }
        try
        {
            e=rs.getInt("ORDERNO");
            e=e+1;
            sqlStatement="insert into orders values("+e+",'"+b+"',"+d+")";
            stmt.executeUpdate(sqlStatement);
            EndPage second= new EndPage();
            second.setVisible(true);
        }
        catch(SQLException x){
            System.out.println(x.getMessage());
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox10;
    private javax.swing.JCheckBox jCheckBox11;
    private javax.swing.JCheckBox jCheckBox12;
    private javax.swing.JCheckBox jCheckBox13;
    private javax.swing.JCheckBox jCheckBox14;
    private javax.swing.JCheckBox jCheckBox15;
    private javax.swing.JCheckBox jCheckBox16;
    private javax.swing.JCheckBox jCheckBox17;
    private javax.swing.JCheckBox jCheckBox18;
    private javax.swing.JCheckBox jCheckBox19;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox20;
    private javax.swing.JCheckBox jCheckBox21;
    private javax.swing.JCheckBox jCheckBox22;
    private javax.swing.JCheckBox jCheckBox23;
    private javax.swing.JCheckBox jCheckBox24;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox31;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
